### ISSUE TITLE
Unfortunately no go but different errors.

### ISSUE THREAD

**Issue by slingshot74** [albaintor/homeassistant_electrolux_status#12]
Unfortunately no go but different errors after installing v1.0.1

Log entry 1:
This error originated from a custom integration.

Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/__init__.py:104
Integration: Electrolux Care Integration V2 (documentation, issues)
First occurred: 14:07:34 (1 occurrences)
Last logged: 14:07:34

'NoneType' object is not iterable
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 104, in setup_entities
    for appliance_json in appliances_list:
TypeError: 'NoneType' object is not iterable

=====
Log record 2

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 14:07:34 (1 occurrences)
Last logged: 14:07:34

Error setting up entry wjpdenouden@gmail.com for electrolux_status
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 104, in setup_entities
    for appliance_json in appliances_list:
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 58, in async_setup_entry
    await coordinator.setup_entities()
  File "/config/custom_components/electrolux_status/__init__.py", line 138, in setup_entities
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

_Originally posted by @slingshot74 in https://github.com/albaintor/homeassistant_electrolux_status/discussions/6#discussioncomment-8360578_

**Comment by dave-prosee** [comment]
V1.0.1 gives 
 File "/Users/daveprosee/Documents/python/core/config/custom_components/electrolux_status/select.py", line 60, in current_option
    label = list(self.options_list.keys())[list(self.options_list.values()).index(value)]
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'ON' is not in list

works on HA git clone with python 3.11 (with above error), but nog on current HA docker distribution with 3.11.

**Comment by bruin14** [comment]
I had the same problem after i updated HA(os) tot 2024.1.6. Rolled back HA tot 2024.1.5 and the integration works again. Maybe this helps

**Comment by tieskuh** [comment]
> I had the same problem after i updated HA(os) tot 2024.1.6. Rolled back HA tot 2024.1.5 and the integration works again. Maybe this helps

The only thing changed between those versions that might be related is: https://github.com/home-assistant/core/pull/109025

**Comment by tieskuh** [comment]
@bruin14 let us know if it keeps working on 2024.1.5

**Comment by bruin14** [comment]
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

I am running above version in a synology VM. I have a dryer and washer, both are detected correctly and work. So the basic of the integration works. The logs shows some erros. If you want me to make an issues of the errors then let me know.

For the rest, i see some entities that give back raw data I think. Not really sure what I should mention about that. 

Anyway, big thks for the development !

**Comment by albaintor** [comment]
It should be fixed now with the last version v1.0.2 or above
