### ISSUE TITLE
Time sync

### ISSUE THREAD

**Issue by sciurius** [albaintor/homeassistant_electrolux_status#16]
I was very unpleasantly surprised to find out that my new, internet connected AEG oven did not have a synchronized clock. I have to set the oven clock manually, and it's a lousy clock -- within a couple of months the difference is already several minutes. As a result, the oven displays a different time than other time-displaying appliances in my home which is confusing and very annoying.

Does anyone know whether it is supposed to work this way? I cannot imagine that in 2023 appliances are made that are fully net connected but do not have time sync.

Will it be possible with the new API to set the appliance time from HomeAssistant?

**Comment by albaintor** [comment]
Hi, I doubt that it would be possible.
You can enable debug level as explained in the discussions to check the capabilities of your oven (capabilities = list of available fields for read or write)
