### ISSUE TITLE
Are alarms for auto-dose tanks not supported yet?

### ISSUE THREAD

**Issue by os11k** [albaintor/homeassistant_electrolux_status#30]
Hi!

First, I would like to thank you for your great work on this integration!

I have 2 auto-dose tanks in my Electrolux EW8F169ASA. It seems that if either of those becomes empty, it is not tracked. Is it possible to add this feature?

**Comment by albaintor** [comment]
Hi, I don't see how I could track this.
You have 2 entities for the 2 tanks or just one ?

**Comment by albaintor** [comment]
I see, alerts could be created dynamically according to capabilities and reported data.
I would not see them as an entity but as a HA persistent notification
<img width="170" alt="image" src="https://github.com/albaintor/homeassistant_electrolux_status/assets/118518828/9807e17b-d50c-4d26-ae94-5d223c950094">

Not my priority though, but feel free to pull a request if you have dev skills and time :-)

**Comment by micro521** [comment]
> Hi!
> 
> First, I would like to thank you for your great work on this integration!
> 
> I have 2 auto-dose tanks in my Electrolux EW8F169ASA. It seems that if either of those becomes empty, it is not tracked. Is it possible to add this feature?

Hi,
I have the exact same machine. I have a sensor for both of the tanks in the itegration.
They are "tank areserve"  and "tank breserve" They are off when the tank has enough fluid anf they are on when the level is low.
Please check if you have it in the sensor list. In the past they had different names.

**Comment by kingy444** [comment]
Tagging https://github.com/albaintor/homeassistant_electrolux_status/issues/48 as similar request

@albaintor 
How does the below look - I have been working on a fairly extensive rework of the integration and have this almost ready to go
![image](https://github.com/albaintor/homeassistant_electrolux_status/assets/7148670/037c6b71-9be3-4ef7-8dc6-b0626c4d6aaf)
![image](https://github.com/albaintor/homeassistant_electrolux_status/assets/7148670/85a482a7-85dc-49ce-ba67-09a8ba77a234)
