### ISSUE TITLE
The timetoend state is never 0

### ISSUE THREAD

**Issue by Palmdale95** [albaintor/homeassistant_electrolux_status#31]
I use an AEG washing machine with the integration provided. This gives me the remaining time in minutes for each wash cycle via the corresponding sensor. However, this sensor is not set to 0 after the end of the wash cycle. The lowest status is 1, but the AEG correctly recognizes that the wash cycle has ended. This was also the case in the old integration.
So is there an error in the transmission to the end of the wash or am I making a mistake?
![tmetoend-washer](https://github.com/albaintor/homeassistant_electrolux_status/assets/111113322/1331e4be-d396-45c1-8e97-3dcb4ad05ef0)

**Comment by albaintor** [comment]
Strange.... I have -1 on my side but never stuck to 1. I checked and I apply ceiling during conversion so that 1,2 minutes become 1, and 0.8 should become 0

**Comment by Palmdale95** [comment]
This is definitely strange. After HA restart it goes to 0. I’ll watch the behavior during the next laundry session next week ;)

**Comment by albaintor** [comment]
I made a minor change to round to 0 if this is less than 0.9 (including negative values)

**Comment by Palmdale95** [comment]
I'll check it out these days and will come back with feedback. Thanks in advance.

**Comment by kfjellerup** [comment]
I'm also experiencing this. It seems like that when the cleaning/drying finishes the integration looses connection to the API. This connection isn't working again until a restart of HA.

I'm also just in general experiencing that the integration stops updating.

**Comment by Palmdale95** [comment]
mmh. now I tried another laundry session and I have no sensor information at all anymore. At least time to end is 0 now :-)

**Comment by albaintor** [comment]
Hi,
do you see any log message when this happens ? I don't have this problem on my side (when laundry ends)
Can you enable loglevel debug and report back ?
In config/configuration.yaml
Then restart HA
```yaml
logger:
  default: warning
  logs:
    custom_components.electrolux_status: debug
```

**Comment by Palmdale95** [comment]
I did not see any logs. It looks like the integration was offline. I made the upgrade to Core 2024.2.2 and then restarted the integration once more. After that my node red integration, which gives me a note when the washer is finished responded to Washer finished. So I guess for now that something was hung up. I'll will check this once more on the next session which supposingly will be on Monday (relying on my wife ;-)) and report back. It is really strange anyway.

**Comment by micro521** [comment]
Hi,
For me it looks like the integration is connected as the appliance status changes but the time to end sensor stays at 1 minute.
![Screenshot_20240218_123932_Home Assistant](https://github.com/albaintor/homeassistant_electrolux_status/assets/95082251/df48acc1-cf25-4e9a-9284-5ce5e1bbb1de)

**Comment by Palmdale95** [comment]
Finished another wahing and time toend stopped again at 1. It looks like there is no real end.

**Comment by Palmdale95** [comment]
The integration is not working propperly. My wife started another session today and the integration did not do anything. 

I extraxted the debug information
[home-assistant_electrolux_status.log](https://github.com/albaintor/homeassistant_electrolux_status/files/14347582/home-assistant_electrolux_status.log)

**Comment by Palmdale95** [comment]
Still same issue: 
![Screenshot 2024-02-29 135817](https://github.com/albaintor/homeassistant_electrolux_status/assets/111113322/39797169-0188-40fd-86aa-b6e214a97855)

**Comment by albaintor** [comment]
I have released a [new version](https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v1.0.13) which fixes the token renewal, maybe it will fix this problem but I am not sure. To be confirmed

**Comment by micro521** [comment]
> I have released a [new version](https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v1.0.13) which fixes the token renewal, maybe it will fix this problem but I am not sure. To be confirmed

I tested it but unfortunately the time to end stops counting at 1 min.

**Comment by Palmdale95** [comment]
In my case it is still stopping at 1 as well. The updates did not cover the issue :-(

**Comment by albaintor** [comment]
The end is not transmitted so will have to trigger manual update when this happens

**Comment by albaintor** [comment]
It is fixed (I think) in the last release. Please confirm

**Comment by Palmdale95** [comment]
You were lucky. It was just a maschine running ;-) and it looks like it finally worked out. Perfect!

**Comment by slingshot74** [comment]
Looks like indeed it's working. Great!
Thanks!

**Comment by albaintor** [comment]
Great !
