### ISSUE TITLE
Time to end changes not in logbook

### ISSUE THREAD

**Issue by slingshot74** [albaintor/homeassistant_electrolux_status#32]
Does any one know why to the changes of the time to end sensor are not in the logbook?
![image](https://github.com/albaintor/homeassistant_electrolux_status/assets/125136823/5e156bba-44e8-4640-a842-4b7e6687fe96)

The sensor is there because I use it on a dashboard
Here it's 105:
![image](https://github.com/albaintor/homeassistant_electrolux_status/assets/125136823/16225312-787c-43e4-93fb-516f4dc772c8)

**Comment by allistermaguire** [comment]
Hi @slingshot74, here is some info from the logbook page https://www.home-assistant.io/integrations/logbook

Sensor entities that have been assigned units (i.e., have a unit_of_measurement attribute) are assumed to change frequently and those sensors are automatically excluded from the logbook.

**Comment by slingshot74** [comment]
@allistermaguire Ah thank you very much for the explanation!
