### ISSUE TITLE
"Appliance total working time" wrong unit

### ISSUE THREAD

**Issue by DragonQ** [albaintor/homeassistant_electrolux_status#36]
Our dryer's "appliance total working time" has a value of 4,852,800 minutes, which is impossible. The unit is probably meant to be **seconds** because 4,852,800 seconds is 56.2 days, which sounds about right given our dryer has been running for 3 hours nearly every day for about 16 months (16x30x3 = 1440 hours = 60 days).

**Comment by albaintor** [comment]
Thank you I merged it
