### ISSUE TITLE
option question

### ISSUE THREAD

**Issue by Marxxu3ru** [albaintor/homeassistant_electrolux_status#40]
My device, the ULTIMATEHOME 500 AP, has only two real control options: manual and smart. However, there are five options for HA integration. Is there any way to remove unnecessary options?
![Uploading IMG_2200.png…]()

**Comment by Marxxu3ru** [comment]
![IMG_2200](https://github.com/albaintor/homeassistant_electrolux_status/assets/139950719/5b153a57-62e8-4352-a2ee-9c977c7f8a95)

**Comment by albaintor** [comment]
I’ll check after. I guess this is because I added supposedly common entities
