### ISSUE TITLE
Water usage?

### ISSUE THREAD

**Issue by bipsendk** [albaintor/homeassistant_electrolux_status#50]
On my washer there is a sensor in HA for water usage.

What does this number indicate ? The number of liters of water being used for the current cycle ?

The formatting/type might be wrong - as I would have expected to see a graph when clicking on it to get the details- but I get a timeline with the different numbers instead.

**Comment by kingy444** [comment]
This one is really going to be a bit of trial and error to work out. There is no clear answer from the API

For instance my fridge has 2 entities similar for water filter and for air filter age.

I worked out the shed based on the info in the Electrolux app and translated to what I could see in HA / API

Likely hood is the value is in litres

**Comment by bipsendk** [comment]
Usage is in liters
