### ISSUE TITLE
Include Temperature Sensors

### ISSUE THREAD

**Issue by Minius90** [albaintor/homeassistant_electrolux_status#51]
I have an AEG RME954F9VX french door refrigerator and thought I would give it a try. Some sensors actually work - thanks for that! Great work!

I receive: Air filter lifetime and -state, water filter flow (I think this is in liters), water filter life time and -state, defrost routine state, humidity, and main board sw version, as well as WIFI connectivity state and link quality indicator.

I wanted to ask if it is possible to add more sensors. I would be interested in three temperature sensors that can be seen in the AEG (Electrolux) app: Refrigerator temperature, the temperature of the first drawer and the freezer compartment temperature.

**Comment by albaintor** [comment]
Hi,
normally all the available sensors are added. If you have doubts, there is a python script provided by the integration
https://github.com/albaintor/homeassistant_electrolux_status/blob/main/testAppliance.py

You can try it (after installing python on your system) after having modified the credentials in the script.
You should be able to see all the available features/fields reported by your appliance

**Comment by Minius90** [comment]
Hi! Thank you very much! I also turned on debug mode and saw some values that are not available as a sensor. How can I turn them into sensors? As far as i could see, it is the data after " 'fridge': " , " 'iceMaker': " and " 'frezer': "

`2024-05-03 05:46:53.982 DEBUG (MainThread) [custom_components.electrolux_status] Electrolux updated reported data {'applianceId': '###', 'applianceData': {'applianceName': '###', 'created': '2024-04-22T20:03:28.796Z', 'modelName': 'CR'}, 'properties': {'desired': {}, 'reported': {'defrostRoutineState': 'WAIT', 'applianceInfo': {'applianceType': 'CR'}, 'fridge': {'alerts': [], 'doorState': 'CLOSED', 'fastModeTimeToEnd': 0, 'fastMode': 'OFF', 'targetTemperatureF': 37.4, 'targetTemperatureC': 3.0, 'applianceState': 'RUNNING'}, 'ui2LockMode': False, 'uiLockMode': False, 'sabbathMode': 'OFF', 'extraCavity': {'fanState': 0}, 'vacationHolidayMode': 'OFF', 'applianceMode': 'NORMAL', 'applianceMainBoardSwVersion': 'JHB10V00', 'alerts': [], 'iceMaker': {'defrostTemperatureC': -20.5, 'defrostTemperatureF': -4.899999999999999}, 'waterFilterState': 'GOOD', 'waterFilterLifeTime': 895299, 'waterFilterFlow': 39.0, 'networkInterface': {'swVersion': 'v5.4.2', 'linkQualityIndicator': 'GOOD', 'otaState': 'IDLE', 'niuSwUpdateCurrentDescription': 'A07491702B-S00008607A', 'swAncAndRevision': 'S00008607A'}, 'airFilterLifeTime': 895299, 'sensorHumidity': 47, 'freezer': {'alerts': [], 'doorState': 'CLOSED', 'fastModeTimeToEnd': 0, 'fastMode': 'OFF', 'targetTemperatureF': -0.3999999999999986, 'targetTemperatureC': -18.0, 'applianceState': 'RUNNING'}, 'airFilterState': 'GOOD', 'reminderTime': -1, 'connectivityState': 'connected'}, 'metadata': {}}, 'status': 'enabled', 'connectionState': 'connected'}`

**Comment by Minius90** [comment]
I found a solution: I changed line 39 in const.py 
from COMMON_ATTRIBUTES = ["connectivityState", "networkInterface/linkQualityIndicator", "applianceMode"]
to COMMON_ATTRIBUTES = ["connectivityState", "networkInterface/linkQualityIndicator", "applianceMode", "fridge/targetTemperatureC", "iceMaker/defrostTemperatureC", "freezer/targetTemperatureC", "fridge/doorState", "freezer/doorState"]

works now for me & can be closed
