### ISSUE TITLE
Electrolux Comfort 600

### ISSUE THREAD

**Issue by sochorf** [albaintor/homeassistant_electrolux_status#60]
Great work! Integration successfully communicates with mobile AC Electrolux Comfort 600. I had only one issue with "ambientTemperatureC" attribute. I had to add line "ambientTemperatureC" : [{"access": "read","type": "number"}, None, SensorDeviceClass.TEMPERATURE, UnitOfTemperature.CELSIUS, None, "mdi:thermometer"], to const.py. Now this attribute has right class.

**Comment by albaintor** [comment]
Thanks I have updated the component
