### ISSUE TITLE
Electrolux PerfectCare 800 - Some Entities Missing after version update/release. 

### ISSUE THREAD

**Issue by wgumaa** [albaintor/homeassistant_electrolux_status#69]
After the latest version update, I noticed some entities have disappeared from the integration. 

Based on the card I created for my washing machine the following entities are no longer available: 

1. select.electrolux_userselections_analogspinspeed
2. select.electrolux_userselections_programuid
3. select.electrolux_userselections_analogtemperature

These are ones I use and there maybe others.

**Comment by albaintor** [comment]
Hi,

I am on it

**Comment by albaintor** [comment]
I will have to cleanup extra entities that should be filtered as irrelevant

**Comment by wgumaa** [comment]
Looks good! Thanks @albaintor
