### ISSUE TITLE
No data any more since updating to the last version

### ISSUE THREAD

**Issue by slingshot74** [albaintor/homeassistant_electrolux_status#78]
Hi,

The integration worked really fine.
I have upgraded to the latest version but everything in unknown now.

Do I something wrong?

In have removed the hub and logged in again but that didn't solve the problem.

**Comment by albaintor** [comment]
Hi, can you share home assistant logs in debug level please ?

**Comment by bdb12** [comment]
> Hi, can you share home assistant logs in debug level please ?

Hi. I too am having the same issue. Most sensors are not showing available. I have enabled dubug logging in the integration but I do not where to find the debug logs you want that are pertinent to this integration. 

Are you able to point me in the right direction.

**Comment by mario-pranjic** [comment]
Hi,

Same here after integrationn update.

Mario.

**Comment by albaintor** [comment]
You can enable logs by editing configuration.yaml and then restarting Home assistant :
```yaml
logger:
  default: debug
  logs:
    custom_components.electrolux_status: debug
```

**Comment by albaintor** [comment]
Can you test again with the latest release : https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v2.0.4

**Comment by kingy444** [comment]
The comments here, are the entities just not available and have an _2 ? Sounds like maybe these are unavailable from the dashboard and haven't checked the integration page?

Suspect this might be another remove and readd the integration to fix 

Note I don't believe you need to reboot or anything, just delete and readd immediately should be fine

**Comment by mario-pranjic** [comment]
OK, I updated to version 2.05. Situation is still the same - most of the sensors are unavilable (not all), as with 2.03.
Example attached.

Best regards,

Mario.
![el-ha](https://github.com/user-attachments/assets/59fc57fc-b684-4cdc-b18b-75b470feb3f8)

**Comment by mario-pranjic** [comment]
I see absolute nothing relevant in logs (mind you, didn't turn debug log atm), besides my template sensors complaining  they can't  reach electrolux sensors where they depend on them.

I do see in Notifications in HA web interface some lines that pop-up which were not seen befire:

Alert: EMPTY_WATER_CONTAINER
Severity: WARNING
Status: NOT_NEEDED

Best regards,

Mario.

**Comment by bdb12** [comment]
I have similar messages to Mario when the dryer is on. Anyway attached are the debug messages. 
[electrolux_status-01J354EY5Q7ZV5ZG8H34EKX0H9-Dryer-711d28b7968abd52240c5bd149ac109d.json](https://github.com/user-attachments/files/17440054/electrolux_status-01J354EY5Q7ZV5ZG8H34EKX0H9-Dryer-711d28b7968abd52240c5bd149ac109d.json)


I have upgraded to 2.05 and I am now on v2024.10.3 of HA. Neither had fixed this.


Dryer alerts
Alert: EMPTY_WATER_CONTAINER
Severity: WARNING
Status: NOT_NEEDED

**Comment by kingy444** [comment]
> OK, I updated to version 2.05. Situation is still the same - most of the sensors are unavilable (not all), as with 2.03.
> 
> Example attached.
> 
> 
> 
> Best regards,
> 
> 
> 
> Mario.
> 
> ![el-ha](https://github.com/user-attachments/assets/59fc57fc-b684-4cdc-b18b-75b470feb3f8)
> 
> 

It looks like sensors have been renamed. Can you delete your integration and readd it

I believe appliance state for instance is now under diagnostic and might even be disabled when you readd the integration (you can manually enable ones you need)

Most of those entities that are unavailable appear to also be in the list of available ones just underneath it

**Comment by kingy444** [comment]
> I have similar messages to Mario when the dryer is on. Anyway attached are the debug messages. 
> 
> [electrolux_status-01J354EY5Q7ZV5ZG8H34EKX0H9-Dryer-711d28b7968abd52240c5bd149ac109d.json](https://github.com/user-attachments/files/17440054/electrolux_status-01J354EY5Q7ZV5ZG8H34EKX0H9-Dryer-711d28b7968abd52240c5bd149ac109d.json)
> 
> 
> 
> 
> 
> I have upgraded to 2.05 and I am now on v2024.10.3 of HA. Neither had fixed this.
> 
> 
> 
> 
> 
> Dryer alerts
> 
> Alert: EMPTY_WATER_CONTAINER
> 
> Severity: WARNING
> 
> Status: NOT_NEEDED

Can you also remove and readd the integration - I suspect that should fix template sensors

Speaking of, can I ask what you were templating (like was it a shortcoming of the integration for instance)

**Comment by bdb12** [comment]
> Dryer alerts
> 
> Alert: EMPTY_WATER_CONTAINER
> 
> Severity: WARNING
> 
> Status: NOT_NEEDED

I too have these messages. I reinstalled the integration, restarting HA in between. It's in a far better state but still these messages.

[electrolux_status-01JAGS3FJX7WK2TNEWBYYJWB6X-Dryer-711d28b7968abd52240c5bd149ac109d.json](https://github.com/user-attachments/files/17441077/electrolux_status-01JAGS3FJX7WK2TNEWBYYJWB6X-Dryer-711d28b7968abd52240c5bd149ac109d.json)

**Comment by kingy444** [comment]
> > Dryer alerts
> 
> > 
> 
> > Alert: EMPTY_WATER_CONTAINER
> 
> > 
> 
> > Severity: WARNING
> 
> > 
> 
> > Status: NOT_NEEDED
> 
> 
> 
> I too have these messages. I reinstalled the integration, restarting HA in between. It's in a far better state but still these messages.
> 
> 
> 
> [electrolux_status-01JAGS3FJX7WK2TNEWBYYJWB6X-Dryer-711d28b7968abd52240c5bd149ac109d.json](https://github.com/user-attachments/files/17441077/electrolux_status-01JAGS3FJX7WK2TNEWBYYJWB6X-Dryer-711d28b7968abd52240c5bd149ac109d.json)
> 
> 

Those are coming from the api so not an error - see https://github.com/albaintor/homeassistant_electrolux_status/issues/72 for more info

Unsure if you can dismiss them in the Electrolux app, but as far as the API is concerned there is an active warning. Until that is resolved it will keep alerting

For instance, I can't dismiss an alert that my fridge door was left open, I must close the door to dismiss it

**Comment by slingshot74** [comment]
> > > Dryer alerts
> > 
> > 
> > > 
> > 
> > 
> > > Alert: EMPTY_WATER_CONTAINER
> > 
> > 
> > > 
> > 
> > 
> > > Severity: WARNING
> > 
> > 
> > > 
> > 
> > 
> > > Status: NOT_NEEDED
> > 
> > 
> > I too have these messages. I reinstalled the integration, restarting HA in between. It's in a far better state but still these messages.
> > [electrolux_status-01JAGS3FJX7WK2TNEWBYYJWB6X-Dryer-711d28b7968abd52240c5bd149ac109d.json](https://github.com/user-attachments/files/17441077/electrolux_status-01JAGS3FJX7WK2TNEWBYYJWB6X-Dryer-711d28b7968abd52240c5bd149ac109d.json)
> 
> Those are coming from the api so not an error - see #72 for more info
> 
> Unsure if you can dismiss them in the Electrolux app, but as far as the API is concerned there is an active warning. Until that is resolved it will keep alerting
> 
> For instance, I can't dismiss an alert that my fridge door was left open, I must close the door to dismiss it

It is an idea not to.send the warning when the status is not needed link in this example..the dryer is connected to a drain so I never have to empty the water tank

**Comment by mario-pranjic** [comment]
OK, I removed hub from integration and added it again. It is working again. Some minor changes in sensors.

Thanks!

Best regards,

Mario.
