### ISSUE TITLE
Target temperature missing after update

### ISSUE THREAD

**Issue by Imperial-Guard** [albaintor/homeassistant_electrolux_status#83]
Sorry once again a comment from my end :) However in the latest version for KSK998230T oven the target temperature is missing. 

While program can be changed is the target temperature missing: "targetTemperatureC": 150.0"

**Comment by albaintor** [comment]
Hi, do you have the possibility to send the data corresponding to your appliance ?

You can execute this python script (change credentials) :
```python
import asyncio
import json
from pyelectroluxocp import OneAppApi
import re

# Fill in your username and password here :
login="xxx"
password="xxx"

async def main():
    async with OneAppApi(login, password) as client:
        appliances = await client.get_appliances_list()
        print("get_appliances_list :\n",json.dumps(appliances, indent=2))

        info = await client.get_appliance_status(appliances[0].get("applianceId"))
        json_object = json.dumps(info, indent=2)
        print("get_appliance_status :\n", json_object)

        info = await client.get_appliance_capabilities(appliances[0].get("applianceId"))
        json_object = json.dumps(info, indent=2)
        print("get_appliance_capabilities :\n", json_object)

        # Writing to sample.json
        # with open("results.json", "w") as outfile:
        #     outfile.write(json_object)
        #
        # def state_update_callback(a):
        #     print("appliance state updated", json.dumps((a)))
        # await client.watch_for_appliance_state_updates([appliances[0].get("applianceId")], state_update_callback)

        #await asyncio.sleep(100)

asyncio.run(main())
```

**Comment by albaintor** [comment]
Yes everything is here and still the entity is not created. Can you also send me the HA logs please ? I would like to track down which attribute failed the creation

**Comment by kingy444** [comment]
@albaintor just ask for diagnostics for that data now too 😀 (json is all in there)

**Comment by kingy444** [comment]
@Imperial-Guard  i also see no need for it to not be created - is it perhaps been goven a new `_2` id ? Not sure if we already removed and readded your integration in that other issue or not.

entity_id format changed so its worth a remove and readd to clean that up

you should be able to go "configure" - copy the password, delete that one and immediately add a new entry with your email and password. reboot shouldnt be required

**Comment by Imperial-Guard** [comment]
Did the following; 

- deleted / removed the current hub without reboot (No effect) 
- deleted / removed the current hub with reboot (No effect) 

[config_entry-electrolux_status-01JAJ3S9XVKSJHQ6FV9P4QXJAX.json](https://github.com/user-attachments/files/17444644/config_entry-electrolux_status-01JAJ3S9XVKSJHQ6FV9P4QXJAX.json)

**Comment by tok1satsu1** [comment]
Same here, missing targetTemperatureC for an A/C Electrolux.

**Comment by albaintor** [comment]
It reminds me I had a hard time with the particular field in the V1, I have to do some archeology.

**Comment by albaintor** [comment]
Hi again @Imperial-Guard I have not found out why the temperature field won't raise.
Can you send me the debug logs of the startup of the integration in order to get the calculated mapping, especially this line :
"Electrolux get_entity. entity_type: %s entity_name: %s entity_attr: %s entity_source: %s capability: %s device_class: %s unit: %s"

Thanks

**Comment by Imperial-Guard** [comment]
[home-assistant_2024-10-30T07-16-30.787Z.log](https://github.com/user-attachments/files/17567563/home-assistant_2024-10-30T07-16-30.787Z.log)

Hi @albaintor, please see attached the complete debug from startup. Thanks :)

**Comment by albaintor** [comment]
> [home-assistant_2024-10-30T07-16-30.787Z.log](https://github.com/user-attachments/files/17567563/home-assistant_2024-10-30T07-16-30.787Z.log)
> 
> Hi @albaintor, please see attached the complete debug from startup. Thanks :)

Thanks
This is strange according to your logs, the target temperature sensor is instanciated
`Electrolux get_entity. entity_type: sensor entity_name: targetTemperatureC entity_attr: targetTemperatureC entity_source:  capability: ...`
`Mijn oven target temperature c `

You don't see it at all ?

**Comment by Imperial-Guard** [comment]
![image](https://github.com/user-attachments/assets/da1dc0ad-5a62-4595-8547-8febbf306500)

@albaintor I guess there is a misunderstanding. However I see the sensor "Target Temperature" but with the update I'm missing the option to set the "Target Temperature" 

See also attached screendump, hopefully this will clarify

**Comment by tok1satsu1** [comment]
> @albaintor I guess there is a misunderstanding. However I see the sensor "Target Temperature" but with the update I'm missing the option to set the "Target Temperature"
> 
![electrolux](https://github.com/user-attachments/assets/3ff3b8ba-815e-4789-af21-1c48943ff979)

Same problem here. I see the target temperature sensor but lost the ability to set the target temperature, like was before. Using 2.0.7 version.

**Comment by kingy444** [comment]
yea pretty sure i found the issue - ill put through a PR shortly
