### ISSUE TITLE
Adding Autodose tank low entitites

### ISSUE THREAD

**Issue by miguelangel-nubla** [albaintor/homeassistant_electrolux_status#86]
In the original integration I added support for autodose tank low entities:

https://github.com/miguelangel-nubla/homeassistant_electrolux_status/commit/386a02184320df2c85bad9097c3109a67481fe15#diff-ea2e7a212f400d287ee6f7be85be80a92c935f1fd68dcba665c6db7d9d012bad

In order to make them available in this new one, I added the definition for the sensors
```
    "fCMiscellaneousState/tankAReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:washing-machine-alert",
    ),
    "fCMiscellaneousState/tankBReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:washing-machine-alert",
    ),
```

but found out `fCMiscellaneousState` is explicitly ignored in `const.py`
```
IGNORED_ATTRIBUTES: [str] = [ "^fCMiscellaneous.+", "fcOptisenseLoadWeight"]
```

Removing the exclusion works, but as I am not familiar with this new API or the reasons it is explicitly ignored, I would like to know how should I proceed here before submitting a PR.

Is making a exception to the exception in the regex appropiate? Does un-ingoring `fCMiscellaneousState` make sense or does it create issues with other appliances? Is some extra logic to handle specific cases needed?

My L8FEC962Q `fCMiscellaneousState ` contains:
```
    "fCMiscellaneousState": {
        "detergentExtradosage": 40,
        "optisenseResult": 65535,
        "softenerExtradosage": 20,
        "tankADetLoadForNominalWeight": 0,
        "tankAReserve": true,
        "tankBDetLoadForNominalWeight": 0,
        "tankBReserve": false,
        "waterUsage": 0
    },
```

**Comment by albaintor** [comment]
Hi, I have added this exclusion list because there are many "technical" sensors that are useless (eg value always = 65535).
Maybe we can do a good mix of both : apply the exclusion list EXCEPT for the ones that are explicitly defined in the catalog

**Comment by kingy444** [comment]
> Hi, I have added this exclusion list because there are many "technical" sensors that are useless (eg value always = 65535) and pollute the integration. Maybe we can do a good mix of both : apply the exclusion list EXCEPT for the ones that are explicitly defined in the catalog

yep - think this is the best approach.

That actually already works here  😄 
https://github.com/albaintor/homeassistant_electrolux_status/blob/main/custom_components/electrolux_status/api.py#L278-L288
![image](https://github.com/user-attachments/assets/24815a21-b54b-4dfb-abeb-3af99997cd39)

I think the `IGNORE_LIST` and this this tuple should  be merged and then the catalog will work as descirbed

**Comment by albaintor** [comment]
Ok I didn't see that you put an exclude list. I just added a white list next to it in the const.py file and added them back in the catalog
I don't want to break things as we don't make the checks at the same location, can you merge the logic into the const.py file ?

**Comment by albaintor** [comment]
EDIT : Ok I have found how. I do the merge

**Comment by miguelangel-nubla** [comment]
Tested and working, thanks!
