### ISSUE TITLE
Getting faulty notifications after latest update 2.0.5

### ISSUE THREAD

**Issue by ChipMIK1** [albaintor/homeassistant_electrolux_status#87]
![2024-10-20_22-01-05](https://github.com/user-attachments/assets/4435ac09-c0a2-487f-a4d3-03ec5fe4cbe3)
As shown, I'm now getting these false: Water tank not used as tumbler is connected to drain and water tank not used at all, and irrelevant (door on washing machine) notifications in HA after updating to 2.0.5

**Comment by nightcbis** [comment]
![felmeddelande](https://github.com/user-attachments/assets/45bc9067-32f1-41d5-85c2-f9517bd178a7)

I have the same problem. I also have my machine connected to the drain so the tank isn't used.

**Comment by tok1satsu1** [comment]
![ar sala](https://github.com/user-attachments/assets/59dca41c-e784-4760-828a-8e73f8f8514a)

Same here with an AC Electrolux.

**Comment by erwinvana** [comment]
I run in to the same issue, never had a notification , now it automatedly reappears, after dismissing (no restart)
![HA_Notifications](https://github.com/user-attachments/assets/43086097-8a85-47e6-a5b4-524651ee5431)

**Comment by nelbs** [comment]
I have the same problem

**Comment by kingy444** [comment]
This is by design, as the API is throwing errors and not actually something broken in the integration.
https://github.com/albaintor/homeassistant_electrolux_status/pull/88 will cover off ignoring certain alerts from the API

**Comment by dschido** [comment]
You can deselect the sending of notifications in the configuration of the integration.
This should help

**Comment by ChipMIK1** [comment]
> You can deselect the sending of notifications in the configuration of the integration. This should help

Excellent, TY :-) Mine has been quiet for a while now :-)
