### ISSUE TITLE
Auto Dose tank sensors

### ISSUE THREAD

**Issue by micro521** [albaintor/homeassistant_electrolux_status#9]
Hi Albaintor,

I just upgraded to the latest release (v 1.0) and the Auto Dose tank sensors for my washing machine (PerfectCare 800 EW8F169ASA) are now missing. In the release from yesterday they were available as "Tank a reserve" and "Tank b reserve".
![image](https://github.com/albaintor/homeassistant_electrolux_status/assets/95082251/c09491f4-88b1-43fd-90d4-d5e71740b83c)

Is it on purpose?
If you need any more info, plesae let me know.

**Comment by albaintor** [comment]
It should be fixed now

**Comment by micro521** [comment]
It is, Thanks a lot.
