### ISSUE TITLE
All entities "unavailable" after upgrade 1.0.9>2.0.5

### ISSUE THREAD

**Issue by svenholman** [albaintor/homeassistant_electrolux_status#93]
Just updated to 2.0.5 (coming from 1.0.9) using HACS, but now all entities from both washing machine and dryer are unavailable.
Reloaded add-ons and rebooted HA makes no difference. 

Can you assist?

**Comment by tieskuh** [comment]
I have the same problem. What was your solution?

**Comment by OstenTV** [comment]
Same problem here. Re-added my account and now most of the entities are completely gone. Used to have "Time to end", "Appliance state" and much more.
![image](https://github.com/user-attachments/assets/4472826d-879f-4311-a178-a222a532d4e5)
